server:
 port: 8083
 
spring:
  application:
    name: API_GATEWAY 
    
  cloud:
    gateway:
      mvc:
        routes:
        - id: CITIZEN-SERVICE
          uri: //CITIZEN-SERVICE
          predicates:
          - Path=/citizen/**
        - id: VACCINATION-SERVICE
          uri: //VACCINATION-SERVICE
          predicates:
          - Path=/vaccinationcenter/**
  
